{{- if .Values.explorer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "persona-testnet.fullname" . }}-explorer
  labels:
    {{- include "persona-testnet.labels" . | nindent 4 }}
    component: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "persona-testnet.selectorLabels" . | nindent 6 }}
      component: explorer
  template:
    metadata:
      labels:
        {{- include "persona-testnet.selectorLabels" . | nindent 8 }}
        component: explorer
    spec:
      containers:
      - name: explorer
        image: "{{ .Values.explorer.image.repository }}:{{ .Values.explorer.image.tag }}"
        ports:
        - name: http
          containerPort: {{ .Values.explorer.port }}
          protocol: TCP
        env:
        - name: CHAIN_ID
          value: {{ .Values.global.chainId }}
        - name: API_ENDPOINT
          value: "http://{{ include "persona-testnet.fullname" . }}-api:1317"
        - name: RPC_ENDPOINT
          value: "http://{{ include "persona-testnet.fullname" . }}-rpc:26657"
        resources:
          {{- toYaml .Values.explorer.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "persona-testnet.fullname" . }}-explorer
  labels:
    {{- include "persona-testnet.labels" . | nindent 4 }}
    component: explorer
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.explorer.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "persona-testnet.selectorLabels" . | nindent 4 }}
    component: explorer
{{- end }}