# PersonaPass Production Monitoring Configuration
# Enterprise-grade monitoring with comprehensive metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'personapass-production'
    environment: 'production'
    datacenter: 'us-east-1'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Kubernetes API Server monitoring
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes nodes monitoring
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)

  # PersonaPass Wallet Pods
  - job_name: 'personapass-wallet'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: personapass-wallet
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__

  # PersonaPass Blockchain Validators
  - job_name: 'personapass-validators'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_label_type]
      action: keep
      regex: personapass-blockchain;validator
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: validator_name
    - source_labels: [__address__]
      action: replace
      regex: (.+):.*
      replacement: $1:26660
      target_label: __address__
    scrape_interval: 5s

  # PersonaPass Full Nodes
  - job_name: 'personapass-fullnodes'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_label_type]
      action: keep
      regex: personapass-blockchain;fullnode
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: node_name
    - source_labels: [__address__]
      action: replace
      regex: (.+):.*
      replacement: $1:26660
      target_label: __address__
    scrape_interval: 10s

  # Tendermint consensus metrics
  - job_name: 'tendermint-consensus'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      action: keep
      regex: personapass-blockchain
    - source_labels: [__address__]
      action: replace
      regex: (.+):.*
      replacement: $1:26660
      target_label: __address__
    metrics_path: /metrics
    scrape_interval: 5s

  # PersonaPass DID Module specific metrics
  - job_name: 'personapass-did-module'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: personapass-blockchain-api
    - source_labels: [__address__]
      action: replace
      regex: (.+):.*
      replacement: $1:1317
      target_label: __address__
    metrics_path: /cosmos/auth/v1beta1/accounts
    params:
      format: ['prometheus']
    scrape_interval: 30s

  # ZK Proof performance metrics
  - job_name: 'zk-proof-performance'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: personapass-blockchain-api
    metrics_path: /persona/zk/v1/metrics
    scrape_interval: 15s

  # EUDI compliance monitoring
  - job_name: 'eudi-compliance'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: personapass-wallet-service
    metrics_path: /api/eudi/compliance/metrics
    scrape_interval: 60s

  # OpenID4VP/VCI protocol metrics
  - job_name: 'openid-protocols'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: personapass-wallet-service
    metrics_path: /api/openid/metrics
    scrape_interval: 30s

  # WebAuthn biometric authentication metrics
  - job_name: 'webauthn-biometric'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: personapass-wallet-service
    metrics_path: /api/webauthn/metrics
    scrape_interval: 30s

  # System resource monitoring
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: node-exporter
    - source_labels: [__meta_kubernetes_pod_node_name]
      target_label: instance
    scrape_interval: 15s

  # cAdvisor container metrics
  - job_name: 'cadvisor'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  # Kube-state-metrics
  - job_name: 'kube-state-metrics'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: kube-state-metrics
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis-exporter'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: redis-exporter
    scrape_interval: 30s

  # PostgreSQL monitoring (if used for off-chain data)
  - job_name: 'postgres-exporter'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: postgres-exporter
    scrape_interval: 30s

  # Nginx Ingress Controller
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      action: keep
      regex: ingress-nginx
    - source_labels: [__address__]
      action: replace
      regex: (.+):(.+)
      replacement: $1:10254
      target_label: __address__
    scrape_interval: 15s

  # External blackbox monitoring
  - job_name: 'blackbox-external'
    metrics_path: /probe
    params:
      module: [http_2xx, tcp_connect, icmp]
    static_configs:
      - targets:
        - https://personapass.io
        - https://api.personapass.io
        - https://rpc.personapass.io
        - https://monitoring.personapass.io
      - targets:
        - personapass.io:443
        - api.personapass.io:443
        - rpc.personapass.io:26657
      - targets:
        - 8.8.8.8  # External connectivity check
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115

  # SSL certificate expiry monitoring
  - job_name: 'ssl-expiry'
    metrics_path: /probe
    params:
      module: [tls_connect]
    static_configs:
      - targets:
        - personapass.io:443
        - api.personapass.io:443
        - monitoring.personapass.io:443
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
    scrape_interval: 3600s  # Check every hour

  # Cost and resource utilization tracking
  - job_name: 'cost-monitoring'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: cost-analyzer
    scrape_interval: 300s  # 5 minutes

alerting:
  alertmanagers:
    - kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: alertmanager

# Remote write for long-term storage (optional)
remote_write:
  - url: "https://prometheus-remote-write.personapass.io/api/v1/write"
    basic_auth:
      username: "prometheus"
      password_file: "/etc/prometheus/remote-write-password"
    write_relabel_configs:
    - source_labels: [__name__]
      regex: 'up|personapass_.*|tendermint_.*|cosmos_.*'
      action: keep

# Remote read for federated queries (optional)
remote_read:
  - url: "https://prometheus-remote-read.personapass.io/api/v1/read"
    basic_auth:
      username: "prometheus"
      password_file: "/etc/prometheus/remote-read-password"