// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	CreateDid(ctx context.Context, in *MsgCreateDid, opts ...grpc.CallOption) (*MsgCreateDidResponse, error)
	UpdateDid(ctx context.Context, in *MsgUpdateDid, opts ...grpc.CallOption) (*MsgUpdateDidResponse, error)
	DeactivateDid(ctx context.Context, in *MsgDeactivateDid, opts ...grpc.CallOption) (*MsgDeactivateDidResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateDid(ctx context.Context, in *MsgCreateDid, opts ...grpc.CallOption) (*MsgCreateDidResponse, error) {
	out := new(MsgCreateDidResponse)
	err := c.cc.Invoke(ctx, "/persona_chain.did.v1.Msg/CreateDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateDid(ctx context.Context, in *MsgUpdateDid, opts ...grpc.CallOption) (*MsgUpdateDidResponse, error) {
	out := new(MsgUpdateDidResponse)
	err := c.cc.Invoke(ctx, "/persona_chain.did.v1.Msg/UpdateDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeactivateDid(ctx context.Context, in *MsgDeactivateDid, opts ...grpc.CallOption) (*MsgDeactivateDidResponse, error) {
	out := new(MsgDeactivateDidResponse)
	err := c.cc.Invoke(ctx, "/persona_chain.did.v1.Msg/DeactivateDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateDid(context.Context, *MsgCreateDid) (*MsgCreateDidResponse, error)
	UpdateDid(context.Context, *MsgUpdateDid) (*MsgUpdateDidResponse, error)
	DeactivateDid(context.Context, *MsgDeactivateDid) (*MsgDeactivateDidResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateDid(context.Context, *MsgCreateDid) (*MsgCreateDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDid not implemented")
}

func (*UnimplementedMsgServer) UpdateDid(context.Context, *MsgUpdateDid) (*MsgUpdateDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDid not implemented")
}

func (*UnimplementedMsgServer) DeactivateDid(context.Context, *MsgDeactivateDid) (*MsgDeactivateDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateDid not implemented")
}

func RegisterMsgServer(s *grpc.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "persona_chain.did.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDid",
			Handler:    _Msg_CreateDid_Handler,
		},
		{
			MethodName: "UpdateDid",
			Handler:    _Msg_UpdateDid_Handler,
		},
		{
			MethodName: "DeactivateDid",
			Handler:    _Msg_DeactivateDid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persona_chain/did/v1/tx.proto",
}

func _Msg_CreateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persona_chain.did.v1.Msg/CreateDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDid(ctx, req.(*MsgCreateDid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateDid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persona_chain.did.v1.Msg/UpdateDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateDid(ctx, req.(*MsgUpdateDid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeactivateDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeactivateDid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeactivateDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persona_chain.did.v1.Msg/DeactivateDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeactivateDid(ctx, req.(*MsgDeactivateDid))
	}
	return interceptor(ctx, in, info, handler)
}