# NGINX Ingress with SSL termination for PersonaChain
# This provides immediate HTTPS endpoints to resolve Mixed Content errors

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Install cert-manager for automatic SSL certificates
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Allow larger request bodies for blockchain transactions
  proxy-body-size: "50m"
  proxy-connect-timeout: "60s"
  proxy-send-timeout: "60s"
  proxy-read-timeout: "60s"
  # Enable CORS for wallet connections
  enable-cors: "true"
  cors-allow-origin: "https://personapass.xyz,https://wallet-om0pm8er6-aiden-lipperts-projects.vercel.app"
  cors-allow-methods: "GET, POST, OPTIONS"
  cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
---
# ClusterIssuer for Let's Encrypt certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@personachain.xyz
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Ingress for RPC endpoint (port 26657)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personachain-rpc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Blockchain-specific configurations
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60" 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    # Enable CORS for wallet connections
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://personapass.xyz,https://wallet-om0pm8er6-aiden-lipperts-projects.vercel.app"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  tls:
  - hosts:
    - rpc.personachain.xyz
    secretName: personachain-rpc-tls
  rules:
  - host: rpc.personachain.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personachain-service
            port:
              number: 26657
---
# Ingress for REST API endpoint (port 1317)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personachain-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # API-specific configurations
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    # Enable CORS for wallet connections
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://personapass.xyz,https://wallet-om0pm8er6-aiden-lipperts-projects.vercel.app"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  tls:
  - hosts:
    - api.personachain.xyz
    secretName: personachain-api-tls
  rules:
  - host: api.personachain.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personachain-service
            port:
              number: 1317