global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20

chains:
  persona-chain-1:
    type: cosmos
    value:
      key: persona-relayer
      chain-id: persona-chain-1
      rpc-addr: http://localhost:26657
      account-prefix: persona
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01stake
      min-gas-amount: 1000
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: 118
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []

  persona-chain-2:
    type: cosmos
    value:
      key: persona-relayer
      chain-id: persona-chain-2
      rpc-addr: http://localhost:36657
      account-prefix: persona
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01stake
      min-gas-amount: 1000
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: 118
      signing-algorithm: ""
      broadcast-mode: batch
      min-loop-duration: 0s
      extension-options: []

paths:
  persona-did-channel:
    src:
      chain-id: persona-chain-1
      client-id: 07-tendermint-0
      connection-id: connection-0
    dst:
      chain-id: persona-chain-2
      client-id: 07-tendermint-0
      connection-id: connection-0
    src-channel-filter:
      rule: allowlist
      channel-list:
        - channel-0
        - channel-1

  persona-vc-channel:
    src:
      chain-id: persona-chain-1
      client-id: 07-tendermint-1
      connection-id: connection-1
    dst:
      chain-id: persona-chain-2
      client-id: 07-tendermint-1
      connection-id: connection-1
    src-channel-filter:
      rule: allowlist
      channel-list:
        - channel-2
        - channel-3