apiVersion: v2
name: persona-testnet
description: Persona Chain 4-node public testnet deployment
type: application
version: 0.1.0
appVersion: "v1.0.0"
keywords:
  - blockchain
  - cosmos
  - zk-proof
  - did
  - verifiable-credentials
home: https://persona-chain.dev
sources:
  - https://github.com/persona-chain/persona-chain
maintainers:
  - name: Persona Chain Team
    email: dev@persona-chain.dev