version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  github-connector:
    build:
      context: .
      dockerfile: github/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./github/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./github:/app
      - /app/node_modules

volumes:
  redis_data:
